#!/bin/bash
#About this script
clear
echo -e "\e[34;5m    ==={}==={}  Lunoxx Impostor  {}==={}==="
echo -e ""
echo -e ""
echo -e "\e[37;5m☛,  Script ini saya buat hasil dari 40% sample-"
echo -e "☛,  KleKlai dan 10% sample Angristan."
echo -e "☛,  Memperbaiki fungsi-fungsi yang tidak bekerja."
echo -e "☛,  Menambahkan fitur untuk kenyamanan memakai script."
echo -e ""
echo -e "☛,  Jika terdapat bug pada script ini,-"
echo -e "☛,  mohon dilaporkan ke kontak dibawah ini."
echo -e ""
echo -e ""
          echo -e "        ---------------------------------------"
          echo -e "             Terimakasih sudah menggunakan-"
          echo -e "                Lunoxx Impostor"
          echo -e "        ---------------------------------------"
echo -e "\e[34;5m"
echo -e "    ==={}==={} My Bot  : t.me/proffrose_bot {}==={}==="
echo -e "    ==={}==={} My Tele : t.me/lunoxximpostor     {}==={}==="
echo -e "\e[37;5m"
